### ISSUE TITLE
Dump file contains whole posgresql database not only configuration  

### ISSUE THREAD

**Issue by bilbolodz** [npotorino/zabbix-backup#15]
Enviroment: postgresql and timescaledb extension

Without option: "-S public" zabbix-backup dump whole database (including hypertables) not only "configuration tables".
Help suggest that's default option so I decided to skip it and it turned out that my backups are growing....

**Comment by ironbishop** [comment]
yep, linked to #13, i was already using `-S public` before the change, that's why I didn't notice
